version: 2.1 # CircleCI version
orbs:
  browser-tools: circleci/browser-tools@0.1.4
  node: circleci/node@1.1.6
jobs:
  build:
    machine:
      image: ubuntu-1604:201903-01

    working_directory: ~/repo # Default working directory, where your project will be cloned

    steps:
      - checkout

      - browser-tools/install-firefox

      - browser-tools/install-chrome:
          replace-existing: true

      - node/install-node:
          version: "12.14.0"

      - run: cd ./docker/ci && KEY_AUTH_SIGN=${MFT_AUTH_KEY} docker-compose up -d

      - run: cd ./test-api && npm install
      - run: cd ./test-api && KEY_AUTH_SIGN=${MFT_AUTH_KEY} npm run ci-test-api && npm run ci-report-api
      - store_artifacts:
          path: ~/repo/test-api/reports

      - run: cd ./test-front && npm install
      - run: cd ./test-front && KEY_AUTH_SIGN=${MFT_AUTH_KEY} npm run ci-test-chrome && npm run ci-report-chrome
      - run: cd ./test-front && KEY_AUTH_SIGN=${MFT_AUTH_KEY} npm run ci-test-firefox && npm run ci-report-firefox
      - store_artifacts:
          path: ~/repo/test-front/reports