version: 2.1 # CircleCI version
orbs:
  browser-tools: circleci/browser-tools@0.1.4
  node: circleci/node@1.1.6
jobs:
  build:
    machine:
      image: ubuntu-1604:201903-01

    working_directory: ~/repo # Default working directory, where your project will be cloned

    steps:
      - checkout

      - browser-tools/install-firefox

      - browser-tools/install-chrome:
          replace-existing: true

      - node/install-node:
          version: "12.14.0"

      - run: cd ./docker/ci && docker-compose up -d

      - run: cd ./test-api && npm install
      - run: cd ./test-api && npm run dock-dev
      - run: cd ./test-api && node reporting.js
      - store_artifacts:
          path: ~/repo/test-api/reports

      - run: cd ./test-front && npm install
      - run: cd ./test-front && npm run dock-dev
      - run: cd ./test-front && node reporting.js
      - store_artifacts:
          path: ~/repo/test-front/reports