version: "3"

services:

  client:
    build:
      context: ../../front
      args:
        - DOCKER_ENV=dock-ci
    ports:
      - ${FRONT_PUBLIC_PORT}:80
    depends_on: 
      - server

  server:
    build: ../../rest
    ports:
      - ${SERVER_PUBLIC_PORT}:3000
    depends_on: 
      - server-database
      - server-fake-smtp
    environment:
      - DEBUG=mft-back:*
      - NODE_ENV=dock-ci
      - KEY_AUTH_SIGN
    
  server-database:
    image: mongo:4.2.24-rc2-bionic
    ports:
      - 27017:27017
    
  server-fake-smtp:
    image: reachfive/fake-smtp-server
    ports:
      - 1025:1025
      - 1080:1080

    