version: "3.5"

services:

  config:
    image: public.ecr.aws/q0f4v2r9/cantlose:${CONFIG_HANDLER_DOCKER_IMAGE_NAME}
    container_name: config
    command: sh -c '/bin/wait-for-it.sh ${RABBIT_SHORT_URL} --timeout=40 -- node app.js'
    ports:
      - 3001:3001
    environment:
      - DEBUG=config-handler:*
      - NODE_ENV=staging
    secrets:
      - external_config

secrets:
  external_config:
    name: arn:aws:secretsmanager:eu-west-3:914445634489:secret:ConfigHandlerSecrets-ynWmk4
    external: true
