apiVersion: v1
kind: Service
metadata:
  name: mft-invc-staging-database
spec:
  type: ClusterIP
  selector:
    app: mft-invc-staging-database
  ports:
    - protocol: TCP
      port: 27017
      targetPort: 27017
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: mft-invc-staging-database
  name: mft-invc-staging-database
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mft-invc-staging-database
  template:
    metadata:
      labels:
        app: mft-invc-staging-database
    spec:
      containers:
      - image: mongo
        name: mft-invc-staging-database
        ports:
        - containerPort: 27017